platform :ios, '8.0'
use_frameworks!
 
target 'BarcodeScanning' do
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Moltin', :git => 'https://github.com/moltin/ios-sdk.git', :branch => 'master'
end
