platform :ios, '9.0'
use_frameworks!
 
target 'BarcodeScanning' do
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Moltin', :git => 'https://github.com/moltin/ios-sdk.git', :branch => 'master'
  pod 'SDWebImage', '~>3.7'
  pod 'SlideMenuControllerSwift'
  pod 'Stripe'
  pod 'Alamofire'
  pod 'Alamofire-Synchronous', '~> 4.0'
end

